model:
  n_layers: 2                       # number of encoder layers
  bidir: True                       # bidirectional rnn encoder
  attention: dot                    # 
train:
  MAX_LENGTH: 15
  teacher_forcing_ratio: 1.0
  save_dir: ./save
